Traceback (most recent call last):
  File "E:\Users\1127229\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "E:\Users\1127229\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Users\1127229\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_core\utils\__init__.py", line 172, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Users\1127229\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "E:\Users\1127229\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "E:\Users\1127229\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "E:\Users\1127229\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# 1. Condicionales: Dado un nÃºmero, determina si es positivo, negativo o cero.
print ("Ingresa un numero para saber si es positivo, negativo o cero: ")
numero= int(input())
if (numero>0):
    print("El numero seleccionado es Positivo")
elif (numero==0): #else if
    print("El numero seleccionado es Cero")
else:
    print("El numero seleccionado es Negativo")
------------------

----- stdout -----
Ingresa un numero para saber si es positivo, negativo o cero:
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mStdinNotImplementedError[0m                  Traceback (most recent call last)
Cell [1;32mIn[1], line 3[0m
[0;32m      1[0m [38;5;66;03m# 1. Condicionales: Dado un nÃºmero, determina si es positivo, negativo o cero.[39;00m
[0;32m      2[0m [38;5;28mprint[39m ([38;5;124m"[39m[38;5;124mIngresa un numero para saber si es positivo, negativo o cero: [39m[38;5;124m"[39m)
[1;32m----> 3[0m numero[38;5;241m=[39m [38;5;28mint[39m([38;5;28;43minput[39;49m[43m([49m[43m)[49m)
[0;32m      4[0m [38;5;28;01mif[39;00m (numero[38;5;241m>[39m[38;5;241m0[39m):
[0;32m      5[0m     [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mEl numero seleccionado es Positivo[39m[38;5;124m"[39m)

File [1;32m~\AppData\Local\Programs\Python\Python312\Lib\site-packages\ipykernel\kernelbase.py:1260[0m, in [0;36mKernel.raw_input[1;34m(self, prompt)[0m
[0;32m   1258[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39m_allow_stdin:
[0;32m   1259[0m     msg [38;5;241m=[39m [38;5;124m"[39m[38;5;124mraw_input was called, but this frontend does not support input requests.[39m[38;5;124m"[39m
[1;32m-> 1260[0m     [38;5;28;01mraise[39;00m StdinNotImplementedError(msg)
[0;32m   1261[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_input_request(
[0;32m   1262[0m     [38;5;28mstr[39m(prompt),
[0;32m   1263[0m     [38;5;28mself[39m[38;5;241m.[39m_parent_ident[[38;5;124m"[39m[38;5;124mshell[39m[38;5;124m"[39m],
[0;32m   1264[0m     [38;5;28mself[39m[38;5;241m.[39mget_parent([38;5;124m"[39m[38;5;124mshell[39m[38;5;124m"[39m),
[0;32m   1265[0m     password[38;5;241m=[39m[38;5;28;01mFalse[39;00m,
[0;32m   1266[0m )

[1;31mStdinNotImplementedError[0m: raw_input was called, but this frontend does not support input requests.

