Traceback (most recent call last):
  File "E:\Users\1127229\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "E:\Users\1127229\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Users\1127229\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_core\utils\__init__.py", line 172, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Users\1127229\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "E:\Users\1127229\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "E:\Users\1127229\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "E:\Users\1127229\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def sumar(a, b):
    a = convertir_a_numero(a)
    b = convertir_a_numero(b)
    return a + b

print(sumar(5, 3))
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[21], line 6[0m
[0;32m      3[0m     b [38;5;241m=[39m convertir_a_numero(b)
[0;32m      4[0m     [38;5;28;01mreturn[39;00m a [38;5;241m+[39m b
[1;32m----> 6[0m [38;5;28mprint[39m([43msumar[49m[43m([49m[38;5;241;43m5[39;49m[43m,[49m[43m [49m[38;5;241;43m3[39;49m[43m)[49m)

Cell [1;32mIn[21], line 2[0m, in [0;36msumar[1;34m(a, b)[0m
[0;32m      1[0m [38;5;28;01mdef[39;00m [38;5;21msumar[39m(a, b):
[1;32m----> 2[0m     a [38;5;241m=[39m [43mconvertir_a_numero[49m(a)
[0;32m      3[0m     b [38;5;241m=[39m convertir_a_numero(b)
[0;32m      4[0m     [38;5;28;01mreturn[39;00m a [38;5;241m+[39m b

[1;31mNameError[0m: name 'convertir_a_numero' is not defined

